[CLIENT-7577] adding bcp to customize boost namespace
twilio/twilio-boost-build pull request #17
Opened 2020-04-16 06:40 UTC by dmorilha-twilio

Uses boost BCP to rename boost namespace with the version.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2020-04-16 07:13 UTC, berkus approved these changes

2020-04-16 07:15 UTC, berkus requested changes
Could you please rename the commit according to practices?

- remove internal ticket number from public repo
- use https://chris.beams.io/posts/git-commit/ style - capitalise the sentence, use imperative mood, all that.

[Look here](https://github.com/twilio/twilio-boost-build/commits/master) for an example of valid commit messages.

2020-04-16 21:40 UTC, dmorilha-twilio commented
done, I think...

2020-04-17 12:19 UTC, berkus approved these changes

2020-04-17 12:19 UTC, merged